### PR TITLE
Run lint and test scripts on GitHub Actions

### PR DESCRIPTION
**Pull request by nickmccurdy**
Port of https://github.com/reduxjs/cra-template-redux/pull/37 with type checking

It would be good to run this before merging to make sure TS works in CI

### CODE REVIEW

**Comment by nickmccurdy** [comment]
@phryneas

**Comment by phryneas** [comment]
I can't run this before merging since there never were actions for this repo before. Can you verify it in your branch?

**Comment by nickmccurdy** [comment]
That's strange, why is the build running on https://github.com/reduxjs/examples/pull/10?

**Comment by phryneas** [comment]
Ah well I guess I'm just gonna merge it and we'll see.

**Comment by phryneas** [comment]
Ah... now I see. `workflows`, not `worksflow` :rofl:

**Comment by phryneas** [comment]
@nickmccurdy so I've renamed it and it seems that some things are indeed not working yet - could you please take another look when you have the time?

**Comment by nickmccurdy** [comment]
I forgot that CI hasn't been running in this repository until now, and the current Jest config doesn't have any TypeScript transformers. I'll try a PR to fix the configs.

**Pull request merged**
