### PR TITLE
Fix scripts

### LINKED ISSUE #9: type-check scripts doesn't work and lint reports many errors
I cloned the repo, tried to run yarn lint, got 53 fixable errors.  running type-check doesn't work because tsconfig is missing.

### PR DESCRIPTION
**Pull request by nickmccurdy**
Ported from reduxjs/cra-template-redux#12

Fixes #9 

- [x] **prettify** needs to be rerun
- [x] **lint** fails because of different Prettier options
- [x] **test** is missing and should be ported from cra-template-redux
- [x] **type-check** fails because there's no tsconfig

### CODE REVIEW

**Comment by msalahz** [comment]
Any updates about this?

**Comment by nickmccurdy** [comment]
Needs review

**Comment by aamirafridi** [comment]
Cannot wait for this PR :P
Can you add reviewers from the sidebar to send them notification?

**Comment by nickmccurdy** [comment]
I don't have permission to myself

**Comment by beenotung** [comment]
> Can you add reviewers from the sidebar to send them notification?
> I don't have permission to myself

I suppose we can notify the maintainer by tagging them like this: @timdorr

**Comment by timdorr** [comment]
LGTM. Thanks!

**Pull request merged**
