### PR TITLE
Template Packages updated

### PR DESCRIPTION
**Pull request by ArslanMahmoodAnsari**
Issue #34  resolved (Module '@testing-library/react' has no exported member 'fireEvent'.)

### CODE REVIEW

**Comment by baharalidurrani** [comment]
- [X] Tested locally using [CRA Testing a template](https://create-react-app.dev/docs/custom-templates/#testing-a-template)
- [X] The new versions look quite the latest.

**Review by baharalidurrani — APPROVED** [review]
fixes #34

**Review by loralridz — APPROVED** [review]
Solves the error compiler throws **_option 'esModuleInterop'_** when using older version of TS.

**Comment by markerikson** [comment]
Sorry I never got around to dealing with this :(

Should resolved with https://github.com/reduxjs/cra-template-redux-typescript/releases/tag/v2.0.0 .

**Pull request closed without merging**
